title: Sense HAT data logger
hero_image: images/banner.png
description: Create a data-logging device using the Sense HAT hardware and Python
original_url: https://raspberrypi.org/learning/sense-hat-data-logger
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Getting data from the Sense HAT
- title: Writing the data to a file
- title: Adding a header to the CSV file
- title: Recording at specific time intervals
- title: Starting your data logger on boot
- title: "Challenge: selecting the data to be recorded"
